spring:
  application:
    name: ingestion-service

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all

  datasource:
    url: jdbc:postgresql://localhost:5433/iiot
    username: iiot
    password: iiot

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 19380

mqtt:
  broker-url: tcp://localhost:1883
  client-id: ingestion-service
  topic-filter: gateway/+/data

app:
  kafka:
    topic:
      sensor-data-raw: sensor-data-raw
      external-data-raw: external-data-raw
  redis:
    gw-resolve-ttl-minutes: 10
  external:
    sweep-interval-ms: 15000
    query-timeout-seconds: 30
    max-rows-per-run: 500
  encryption:
    key: ${APP_ENCRYPTION_KEY:htcBFqnfOVeXpRFzOHXr3wAl1qRamivL3PBA5IC+hEY=}

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
